version: '3.8'

services:
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    container_name: "mysql-container"
    environment:
        MYSQL_DATABASE: puzzle_platform
        MYSQL_ROOT_PASSWORD: 1
    volumes:
      - myslq-data:/data
  redis:
    image: "redis:latest"
    container_name: "redis-container"
    ports:
      - "6380:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
  myslq-data: